name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with cycloneL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          SHOW_LOC_CHART: False
          SECTION_NAME: waka
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_EDITORS: True
          SHOW_TIMEZONE: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
          SHOW_UPDATED_DATE: True
          SHOW_TOTAL_CODE_TIME: True
          COMMIT_BY_ME: False
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_SINGLE: False
          LOCALE: en
          UPDATED_DATE_FORMAT: %d/%m/%Y %H:%M:%S
          SYMBOL_VERSION: 1
