name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with cycloneL
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@latest
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          # 时间线
          SHOW_LOC_CHART: False
